baseurl = "https://survivallabs.ml/"  # Include trailing slash
title = "Survival Labs™"
theme = "hugo-swift-theme"
author = "David Dilanchian"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 4
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[params]
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1
    # Analytic section
    google_analytics_id = "221430475" # Your Google Analytics tracking id
    tag_manager_container_id = "G-KKVW19F4F9" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console
    
  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  # twitter = "" # twitter handle e.g @weru
  # logo = "logo.png"
  # author = "Weru" # default author
  # image = "placeholder-image.png" # used whenever a page image is not set
  # blogDir = "blogFolderName" # uncomment and edit to exclude normal pages ... see issue #57

# [params.staticman]
#   endpoint = "https://staticman3.herokuapp.com"  # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
#   gitProvider = "github"  # Either "github" or "gitlab"
#   username = "davdegreat"  # GitHub/GitLab user name
#   repository = "survivallabs.ml"  # GitHub/GitLab user name
#   branch = "master"  # Branch holding the source code for your site, should match the `branch` parameter in `staticman.yml`
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>

theme: jekyll-theme-slate